### ISSUE TITLE
MKL error in orbital optimizer

### ISSUE THREAD

**Issue by edeprince3** [edeprince3/hilbert#7]
With the upgrade from fortran->c++ in the orbital optimizer, an bug was introduced such that MKL often returns:

Intel MKL ERROR: Parameter 8 was incorrect on entry to DGEMM .

**Comment by edeprince3** [comment]
I see this error in tests/v2rdm5

**Comment by ggidofal** [comment]
I updated the c++ orbital optimization functions to check for 0-rank matrices upon entry to DGEMM. All the tests pass and I do not get "incorrect parameter" errors from MKL. This issue is somewhat perplexing to me since v2rdm5 uses conventional integrals and  the c++ code should not have worked at all.

I updated v2rdm_solver.cc so that the old fortran code is called for conventional integrals but the new c++ functions are used whenver DF integrals are in use.
